# Generated by Django 6.0.4 on 2026-05-17 22:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'biblioteca_empleado',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_volume_id', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.TextField(blank=True, null=True)),
                ('editorial', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_publicacion', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_paginas', models.IntegerField(blank=True, null=True)),
                ('idioma', models.CharField(blank=True, max_length=10, null=True)),
                ('isbn_10', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn_13', models.CharField(blank=True, max_length=20, null=True)),
                ('portada_url', models.TextField(blank=True, null=True)),
                ('preview_url', models.TextField(blank=True, null=True)),
                ('tipo_impresion', models.CharField(default='BOOK', max_length=20)),
                ('text_snippet', models.TextField(blank=True, null=True)),
                ('cantidad_disponible', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autores', models.ManyToManyField(to='biblioteca.autor')),
                ('generos', models.ManyToManyField(to='biblioteca.genero')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('condicion_libro', models.CharField(blank=True, help_text='Ej: Buen estado, Rayado, Dañado', max_length=100, null=True)),
                ('devuelto', models.BooleanField(default=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Devuelto', 'Devuelto'), ('Retraso', 'Retraso')], default='Activo', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_gestionados', to='biblioteca.empleado')),
                ('libros', models.ManyToManyField(through='biblioteca.DetallePrestamo', to='biblioteca.libro')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='biblioteca.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('motivo', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada')], default='Pendiente', max_length=50)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('prestamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas', to='biblioteca.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('tipo_accion', models.CharField(choices=[('Prestamo', 'Préstamo'), ('Devolucion', 'Devolución'), ('Multa', 'Multa'), ('Moroso', 'Moroso')], max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prestamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='biblioteca.prestamo')),
            ],
            options={
                'verbose_name_plural': 'Historiales',
            },
        ),
        migrations.AddField(
            model_name='detalleprestamo',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestamo'),
        ),
    ]
